### ISSUE TITLE
Issue with Data received from python-emotiv

### ISSUE THREAD

**Issue by Pmarenco** [ozancaglayan/python-emotiv#15]
Actually, more than a issue I have a question. I use your library to communicate my emotiv with matlab, but I don't know what are the data units.
The signals I received have an amplitude about 4000. Are those data in micro Volts?

Sorry if I write bad I don't speak english pretty well
But I hope someone can help me

Thanks

**Comment by ozancaglayan** [comment]
No they are actually quantized values but it doesn't generally matter whether you have integers or you convert them to volts.
